name: flutter_chat
description: flutter chat

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  cupertino_icons: ^1.0.2
  get: 4.6.6
  logger: 2.0.2+1
  fluttertoast: 8.2.2
  dio: 5.3.3
  shared_preferences: 2.2.2
  flutter_svg: 2.0.8
  web_socket_channel: ^2.4.2
  permission_handler: 10.2.0
  easy_refresh: ^3.3.2+1
  cached_network_image: ^3.3.0
  lpinyin: ^2.0.2
#  isar: ^3.1.0+1 # 弃用，功能少，bug多
#  isar_flutter_libs: ^3.1.0+1
  sqflite: ^2.3.2
  path_provider: ^2.1.0
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  record: ^5.0.4
  lottie: ^3.0.0
  just_audio: ^0.9.36
#  pretty_dio_logger: 1.3.1
#  get_it: ^7.6.4
#  flutter_screenutil: 5.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.2
  analyzer: 5.13.0
  dart_code_metrics: any
  change_app_package_name: 1.1.0
  build_runner: ^2.4.6
#  isar_generator: ^3.1.0+1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/voice/
    - assets/anim/


